---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # disable auto PRs since this is a learning project and we want to manually review updates
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # disable auto PRs since this is a learning project and we want to manually review updates
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # disable auto PRs since this is a learning project and we want to manually review updates
    labels:
      - "dependencies"
      - "pre-commit"
    commit-message:
      prefix: "ci"
    groups:
      pre-commit:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      day: "sunday"
      time: "01:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 0
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
